name: Semgrep CI E2E Test
on:
  workflow_dispatch:
  schedule:
    - cron: "20 43 * * *"

jobs:
  semgrep:
    name: Static Analysis Scan
    runs-on: ubuntu-22.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_E2E_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
